apiVersion: apps/v1
kind: Deployment
metadata:
  name: veicule-storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veicule-storage-app
  template:
    metadata:
      labels:
        app: veicule-storage-app
    spec:
      containers:
        - name: veicule-storage-container
          image: diegogl12/veicule-storage:latest
          ports:
            - containerPort: 4000
          env:
            - name: VEICULE_STORAGE_HOSTNAME
              value: postgres-service
            
            - name: VEICULE_STORAGE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            
            - name: VEICULE_STORAGE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            
            - name: VEICULE_STORAGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
