apiVersion: v1
kind: Service 
metadata:
  name: veicule-storage-service
spec:
  type: NodePort 
  selector:
    app: veicule-storage-app 
  ports:
    - port: 80 
      targetPort: 4000 
      nodePort: 30000 
