services:
  database:
    image: postgres:15
    container_name: veicule_storage_database
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - veicule-storage-network

  veicule_storage:
    container_name: veicule_storage
    env_file:
      - .env
    environment:
      - VEICULE_STORAGE_HOSTNAME=veicule_storage_database
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    command: sh -c "mix ecto.create && mix ecto.migrate && mix run --no-halt"
    depends_on:
      database:
        condition: service_started
    networks:
      veicule-storage-network:
        aliases:
          - veicule_storage
    dns_search: .

networks:
  veicule-storage-network:
    name: veicule-storage-network
    driver: bridge
